// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuGRura-O-WiUsWFLctYtuvablpfavNBE',
    appId: '1:750031630648:web:f55cc66ff337d94994d1cd',
    messagingSenderId: '750031630648',
    projectId: 'edulog-88a7f',
    authDomain: 'edulog-88a7f.firebaseapp.com',
    storageBucket: 'edulog-88a7f.firebasestorage.app',
    measurementId: 'G-8EGLY5WTLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3f_XAhKh9FM1avA-55IaTMDkXO9lMTdE',
    appId: '1:750031630648:android:b7ee0bbada5a012a94d1cd',
    messagingSenderId: '750031630648',
    projectId: 'edulog-88a7f',
    storageBucket: 'edulog-88a7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnMQQxXFw4nnE73h2TaSnhGOTWhhJitU8',
    appId: '1:750031630648:ios:f970a6c1a13bf08694d1cd',
    messagingSenderId: '750031630648',
    projectId: 'edulog-88a7f',
    storageBucket: 'edulog-88a7f.firebasestorage.app',
    iosBundleId: 'com.example.edulog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnMQQxXFw4nnE73h2TaSnhGOTWhhJitU8',
    appId: '1:750031630648:ios:f970a6c1a13bf08694d1cd',
    messagingSenderId: '750031630648',
    projectId: 'edulog-88a7f',
    storageBucket: 'edulog-88a7f.firebasestorage.app',
    iosBundleId: 'com.example.edulog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuGRura-O-WiUsWFLctYtuvablpfavNBE',
    appId: '1:750031630648:web:f7a6c5b464be7aaa94d1cd',
    messagingSenderId: '750031630648',
    projectId: 'edulog-88a7f',
    authDomain: 'edulog-88a7f.firebaseapp.com',
    storageBucket: 'edulog-88a7f.firebasestorage.app',
    measurementId: 'G-27N4S8YFF8',
  );
}
